### ISSUE TITLE
Feature request: Use visual mode on single opcode at address

### ISSUE THREAD

**Issue by heasm66** [cspiegel/zdevtools#4]
The visual mode is quite verbose and it would be nice to only inspect a single opcode+operands (I know this can be done with the `-b` switch but it would be nice to get it done with a single address also).

**Comment by cspiegel** [comment]
How would you envision a call for this looking?  I can see this being two unrelated options which you could combine, although  I'm not sure how useful either would be on its own...

Since you're looking for a single instruction then you can't use `-a` or `-A`, given that those expect routines.  So we'd need a new flag to mean "start disassembling at this specific byte offset".

Then you'll also need a flag to limit the number of instructions that you want decoded, which in this case you'd set to 1.

Here's another question: is the goal to decode instructions at arbitrary places in a file, or to decode instructions at known-good addresses?  By this I mean there are two options here:

1. Decode at an arbitrary address: even if it's not an instruction in the game (e.g. you pointed inside of a string), try to decode and see what happens.
2. Decode everything and then display the instruction at the specified address, if it exists.  If it doesn't, display an error.

It would actually be pretty easy, I think, to implement 2.  The work's already done, and now it's just a matter of mangling the instruction list at the end to only contain that which is important.

**Comment by heasm66** [comment]
I envisioned it just like bytestring but you instead supplied an starting address and it decode until it reaches the end of the opcode and the operands associated to that opcode. Much of the time I'm using the visual mode I'm only interested to the bit explaination for a single instruction. Option 2 seemsa like a reasonable solution.

(In a future far away I envision a graphical front-end that lets you examine each single instruction; click on a call to jump to that routine; name routines, globals, locals and other thing in a symbol file; and so on...)

**Comment by cspiegel** [comment]
Thinking on it, option 1 is really better, because zd is not good at finding all addresses in the file (TXD is much better since it "knows" the layout of Infocom and Inform files).  So there would be many valid addresses that would fail if I went with option 2.

There is absolutely utility in pointing to an arbitrary address and decoding.  Worst case, if it's not a valid instruction, is that it looks like gibberish.

I'll figure out how to make zd a bit more general purpose, which will also help to improve the bytestring mode.

**Comment by cspiegel** [comment]
Alright, here's a preview of what I've done.  I added `--start-offset` to choose the absolute offset into a file/bytestring to parse, and `--max-instructions` to limit how many instructions will be decoded.  These can be combined to achieve what you want, I think:

```
$ zd --start-offset 0x9533 --max-instructions 1 zork1.z3

9533: store            G6b L00
```

Or:

```
$ zd -d --start-offset 1 --max-instructions 1 -b b211aac634b4

1: 11 aa c6 34              get_prop         #aa #c6 -> G24
```
It works in visual mode, too:

```
$ zd -v --start-offset 0x9533 --max-instructions 1 zork1.z3
┌────────────────────────────────────────────────────────────────────┐
│9533: store - 2OP                                                   │
└────────────────────────────────────────────────────────────────────┘
┌─ Long form
│ ┌─ First operand: Small constant
│ │ ┌─ Second operand: Variable
│ │ │     ┌─ @store
│ │ │ ┌───┴───┐
0 0 1 0 1 1 0 1 

Operand 1: 01111011 (123)
Operand 2: 00000001 (L00)
```
Does this achieve what you want?

**Comment by cspiegel** [comment]
OK, this is in the newly-release 2.1.0.
